language: node_js
node_js:
  - 10
install:
  - yarn install
  - yarn build
  - cd playground && yarn install && cd ../
script:
  - yarn test
before_deploy:
  - travis_wait 20 yarn build-website
env:
  - CI=true
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: build-website
  github-token: $GITHUB_TOKEN
  fqdn: dprint.dev
  keep-history: true
  on:
    branch: master
