[workspace]
members = [
    "crates/core",
    "crates/development",
    "crates/dprint",
    "crates/dprint-plugin-jsonc",
    "crates/dprint-plugin-typescript"
]
exclude = [
    "crates/test-plugin",
    "packages/dprint-plugin-jsonc/wasm",
    "packages/dprint-plugin-typescript/wasm",
    "packages/playground/wasm"
]
