blank_issues_enabled: false
contact_links:
  - name: TypeScript/JavaScript formatting feature or bug
    url: https://github.com/dprint/dprint-plugin-typescript/issues/new/choose
    about: Please open TypeScript/JavaScript formatting issues here
  - name: JSON formatting feature or bug
    url: https://github.com/dprint/dprint-plugin-json/issues/new/choose
    about: Please open JSON formatting issues here
  - name: Markdown formatting feature or bug
    url: https://github.com/dprint/dprint-plugin-markdown/issues/new/choose
    about: Please open Markdown formatting issues here
