[package]
name = "dprint-cli-core"
version = "0.4.0"
authors = ["David Sherret <dsherret@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Core Dprint CLI library for reuse."
repository = "https://github.com/dprint/dprint"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.18.0"
parking_lot = "0.11.0"
reqwest = { version = "0.10.8", features = ["rustls-tls"] }
sha2 = "0.9.1"
strip-ansi-escapes = "0.1.0"
