[package]
name = "dprint-cli-core"
version = "0.5.3"
authors = ["David Sherret <dsherret@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Core Dprint CLI library for reuse."
repository = "https://github.com/dprint/dprint"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.19.0"
parking_lot = "0.11.0"
sha2 = "0.9.3"
ureq = { version = "2.0.2", features = ["tls"] }
