[package]
name = "dprint"
version = "0.15.0"
authors = ["dprint code formatting <david@dprint.dev>"]
edition = "2018"
license = "MIT"
description = "Binary for dprint code formatter—a pluggable and configurable code formatting platform."
repository = "https://github.com/dprint/dprint"
keywords = ["code-formatter", "formatter"]
categories = ["development-tools"]

[dependencies]
clap = "2.33.3"
crossterm = "0.20.0"
dunce = "1.0.2"
dprint-core = { path = "../core", version = "0.44.0", features = ["process", "wasm"] }
dprint-cli-core = { path = "../cli-core", version = "0.6.0" }
dissimilar = "1.0"
globwalk = "0.8.1"
jsonc-parser = { version = "0.17.0" }
parking_lot = "0.11.1"
dirs = "3.0.2"
num_cpus = "1.13.0"
rayon = "1.5.1"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0"
twox-hash = "1.6.0"
url = "2.2.2"
wasmer = "=2.0.0"
zip = "0.5.13"
wild = "2.0.4"

[target.'cfg(windows)'.dependencies]
winreg = "0.9.0"

[dev-dependencies]
globset = "0.4.8"
lazy_static = "1.4.0"
pretty_assertions = "0.7.2"
path-clean = "0.1.0"
