[package]
name = "dprint"
version = "0.9.1"
authors = ["Dprint Code Formatting <david@dprint.dev>"]
edition = "2018"
license-file = "LICENSE"
description = "Binary for dprint."
repository = "https://github.com/dprint/dprint"

[dependencies]
clap = "2.33.0"
colored = "1.9.3" # todo: remove and use console (it's in dprint-cli-core)
dunce = "1.0.1"
dprint-core = { path = "../core", version = "0.29.0", features = ["process", "wasm"] }
dprint-cli-core = { path = "../cli-core", version = "0.1.0" }
dialoguer = "0.6.2"
dissimilar = "1.0"
globwalk = "0.8.0"
jsonc-parser = { version = "0.14.0" }
indicatif = "0.14.0"
bytes = "0.5.4"
futures = { version = "0.3.4", features = ["compat", "io-compat"] }
tokio = { version = "0.2", features = ["full", "blocking", "sync"] }
async-trait = "0.1.30"
app_dirs = "1.2.1"
serde = { version = "1.0.88", features = ["derive"] }
serde_json = "1.0"
twox-hash = "1.5.0"
url = "2.1.1"
wasmer-runtime = "0.17.0"
wasmer-runtime-core="0.17.0"
zip = "0.5.6"

[dev-dependencies]
globset = "0.4.5"
lazy_static = "1.4.0"
pretty_assertions = "0.6.1"
path-clean = "0.1.0"
