[package]
name = "dprint-development"
description = "Helper functions for testing dprint plugins."
version = "0.2.0"
authors = ["David Sherret <dsherret@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
dprint-core = { path = "../core", version = "0.21.0" }