[package]
name = "dprint-core"
description = "Core rust library for dprint."
keywords = ["formatting", "formatter"]
version = "0.42.0"
authors = ["David Sherret <dsherret@gmail.com>"]
edition = "2018"
license = "MIT"
homepage = "https://github.com/dprint/dprint/tree/main/crates/core"
repository = "https://github.com/dprint/dprint"

[features]
default = ["formatting"]

formatting = ["bumpalo", "fnv"]
process = ["serde_json", "sysinfo"]
wasm = []
tracing = ["formatting"]

[dependencies]
serde = { version = "1.0.126", features = ["derive"] }
serde_json = { version = "1.0", optional = true }
sysinfo = { version = "0.17.5", optional = true }
bumpalo = { version = "3.6.1", optional = true }
fnv = { version = "1.0.7", optional = true }