[package]
name = "dprint-core"
description = "Core library for dprint."
keywords = ["formatting", "formatter"]
version = "0.43.0"
authors = ["David Sherret <dsherret@gmail.com>"]
edition = "2018"
license = "MIT"
homepage = "https://github.com/dprint/dprint/tree/main/crates/core"
repository = "https://github.com/dprint/dprint"

[features]
default = ["formatting"]

formatting = ["bumpalo", "fnv"]
process = ["serde_json", "libc", "winapi"]
wasm = []
tracing = ["formatting"]

[dependencies]
serde = { version = "1.0.126", features = ["derive"] }
serde_json = { version = "1.0", optional = true }
bumpalo = { version = "3.6.1", optional = true }
fnv = { version = "1.0.7", optional = true }

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["handleapi", "synchapi", "winbase", "winerror"], optional = true }

[target.'cfg(not(any(target_os = "unknown", target_arch = "wasm32")))'.dependencies]
libc = { version = "0.2.97", optional = true }
